REDACT_ERROR = "redact_error"
DOCUMENT_CONVERSION_ERROR = "document_conversion_error"
DOCUMENT_CONVERSION_TIMEOUT = "document_conversion_timeout"
INVALID_MIME_TYPE = "invalid_mime_type"
REDACT_TIMEOUT = "redact_timeout"
TASK_NOT_FOUND = "task_not_found"
TASK_QUEUE_FULL = "task_queue_full"
FILE_TOO_LARGE = "file_too_large"
